name: Primeiro CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Compilar:
    # criar maquina virtual para usar no pipeline
    runs-on: ubuntu-latest
    
    steps:
      - name: Fazer o git clone
        uses: actions/checkout@v4

      - name: Executando primeiro comando
        run: echo "Amo DEVOPS:)"
              
      - name: Executando dois ou mais comandos
        run: |
          ls -l
          echo "Fim do PROCESSO"
  
  build:
    # Specify runner +  build & upload the static files as an artifact
    runs-on: ubuntu-latest
    steps:
      - name: Build static files
        id: build
        run: |
          # <Not provided for brevity>
          # At a minimum this step should build the static files of your site
          # <Not provided for brevity>

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: build_outputs_folder/

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
